[package]
name = "pulpissimo-riscv-rt"
version = "0.12.1"
rust-version = "1.60"
repository = "https://github.com/soc-hub-fi/pulpissimo-riscv"
authors = ["Henri Lunnikivi <henri.lunnikivi@tuni.fi>"]
categories = ["embedded", "no-std"]
description = "Minimal runtime / startup for RISC-V CPU's"
documentation = "https://docs.rs/riscv-rt"
keywords = ["riscv", "runtime", "startup"]
license = "ISC"
edition = "2021"
links = "riscv-rt" # Prevent multiple versions of riscv-rt being linked

[features]
s-mode = []
single-hart = []

[dependencies]
riscv = { package = "pulpissimo-riscv", path = "../riscv", version = "0.11.0" }
riscv-rt-macros = { package = "pulpissimo-riscv-rt-macros", path = "macros", version = "0.2.1" }

[dev-dependencies]
panic-halt = "0.2.0"
