[package]
name = "riscv-pac"
version = "0.1.0"
edition = "2021"
rust-version = "1.60"
repository = "https://github.com/soc-hub-fi/pulpissimo-riscv"
authors = ["Henri Lunnikivi <henri.lunnikivi@tuni.fi>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "Low level access to RISC-V processors"
documentation = "https://docs.rs/riscv-pac"
keywords = ["riscv", "register", "peripheral"]
license = "ISC"

[package.metadata.docs.rs]
default-target = "riscv64imac-unknown-none-elf"
targets = [
    "riscv32i-unknown-none-elf", "riscv32imc-unknown-none-elf", "riscv32imac-unknown-none-elf",
    "riscv64imac-unknown-none-elf", "riscv64gc-unknown-none-elf",
]
