[package]
name = "pulpissimo-riscv"
version = "0.11.0"
edition = "2021"
rust-version = "1.60"
repository = "https://github.com/soc-hub-fi/pulpissimo-riscv"
authors = ["Henri Lunnikivi <henri.lunnikivi@tuni.fi>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "Low level access to RISC-V processors"
documentation = "https://docs.rs/riscv"
keywords = ["riscv", "register", "peripheral"]
license = "ISC"

[package.metadata.docs.rs]
all-features = true
default-target = "riscv64imac-unknown-none-elf"
targets = [
    "riscv32i-unknown-none-elf", "riscv32imc-unknown-none-elf", "riscv32imac-unknown-none-elf",
    "riscv64imac-unknown-none-elf", "riscv64gc-unknown-none-elf",
]

[features]
s-mode = []
critical-section-single-hart = ["critical-section/restore-state-bool"]
ballast = []
ballast-sysctrl = ["ballast"]
ballast-mpc = ["ballast"]
tackle = []
headsail-sysctrl = []

[dependencies]
critical-section = "1.1.2"
embedded-hal = "1.0.0"
